## VAGRANT CONFIGURATION. ##
#vagrant_box: ubuntu/trusty64
vagrant_box: ubuntu/precise64
vagrant_hostname: develop
vagrant_ip: 192.168.33.10

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

# Local Folder with the projetcs
local_folder_projects: /Users/javi/Sites/


### ANSIBLE VARS ###
ansible_tags: all

# Apache config
apache_version: 2.2
apache_user: vagrant
apache_group: vagrant

apache_sites: 
  - {host_name: local.dev, host_root: /proyectos/}

# PHP config
php_config_cli:
  - {key: date.timezone, value: Europe/Madrid}

php_config_apache:
  - {key: date.timezone, value: Europe/Madrid}
  - {key: memory_limit, value: 256M}
  - {key: upload_max_filesize, value: 10M}
  - {key: post_max_size, value: 10M}

drush_version: 6.6.0


