# Vagrant hostname and IP configuration.
vagrant_hostname: drupaltest.dev
vagrant_ip: 192.168.33.10

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

# Apache config
apache_user: vagrant
apache_group: vagrant