#roles/sites/tasks/main.yml
---
- name: SITES - delete all sites enableds
  shell: rm -fr /etc/apache2/sites-enabled/*
  notify: restart apache
  tags:
   - sites

- shell: apache2 -v
  register: apache_version
  tags:
   - sites

- name: SITES - Change default apache2.4 site
  template: src=apache_2.4.conf dest=/etc/apache2/sites-enabled/{{ item.host_name }}.conf owner=root group=root force=yes
  with_items: apache_sites
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.4.') != -1 and apache_sites|length > 0
  tags:
   - sites
   
- name: SITES - Change default apache2.2 site
  template: src=apache_2.2.conf dest=/etc/apache2/sites-enabled/{{ item.host_name }}.conf owner=root group=root force=yes
  with_items: apache_sites
  notify: restart apache  
  when: apache_version.stdout.find('Apache/2.2.') != -1 and apache_sites|length > 0
  tags:
   - sites