#roles/sites/tasks/main.yml
---
- name: enable rewrite module
  shell: a2enmod rewrite
  notify: restart apache

- name: delete all sites enableds
  shell: rm -fr /etc/apache2/sites-enabled/*
  notify: restart apache

- name: copy default sites apache
  template: src=apache_{{ apache_version }}.conf dest=/etc/apache2/sites-enabled/{{ item.host_name }}.conf owner=root group=root force=yes
  with_items: apache_sites
  when: apache_sites|length > 0
  notify: restart apache

