#roles/apache/tasks/main.yml
---
- name: Apache - install package
  apt: name=apache2 state=latest

- name: Apache - config envvars apache - user
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_USER=www-data'
              line='export APACHE_RUN_USER={{ apache_user }}'

- name: Apache - config envvars apache - group
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_GROUP=www-data'
              line='export APACHE_RUN_GROUP={{ apache_group }}'

- name: Apache - reset
  command: sudo rm -Rf /var/lock/apache2

- name: Apache | Enable module | Enable $module
  command: a2enmod 'rewrite'
  notify: restart apache
