#roles/apache/tasks/main.yml
---
- name: install package
  apt: name=apache2 state=latest

#- name: copy new envvars
#  template: src=envvars dest=/etc/apache2/envvars owner=root group=root force=yes
#  notify: restart apache

- name: config envvars apache - user
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_USER=www-data'
              line='export APACHE_RUN_USER={{ apache_user }}'
  notify: restart apache

- name: config envvars apache - group
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_GROUP=www-data'
              line='export APACHE_RUN_GROUP={{ apache_group }}'
  notify: restart apache

- name: Apache | Enable module | Enable $module
  command: a2enmod 'rewrite'
  notify: restart apache