#roles/apache/tasks/main.yml
---
- name: APACHE - install package
  apt: name=apache2 state=latest

- name: APACHE - config envvars apache - user
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_USER=www-data'
              line='export APACHE_RUN_USER={{ apache_user }}'

- name: APACHE - config envvars apache - group
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_GROUP=www-data'
              line='export APACHE_RUN_GROUP={{ apache_group }}'

- name: APACHE - reset
  command: sudo rm -Rf /var/lock/apache2

- name: APACHE - Enable modules
  command: a2enmod '{{ item }}'
  with_items: apache_modules
  notify: restart apache
  when: apache_modules|length > 0

