#roles/ubuntu-common/tasks/main.yml
---
- name: COMMON - Adding PPA
  apt_repository: repo={{ item }}
  with_items: ubuntu_apt_repositories

- name: COMMON - Update apt
  apt: update_cache=yes

- name: COMMON - Install System Packages
  apt: name={{ item }} state=latest
  with_items: ubuntu_sys_packages

- name: COMMON - Setting es_ES locale
  shell: locale-gen es_ES.UTF-8

- name: COMMON - Configure the timezone
  template: src=timezone.tpl dest=/etc/timezone

- name: COMMON - More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{ ubuntu_timezone }} dest=/etc/localtime state=link force=yes backup=yes

- name: COMMON - Set the hostname in /etc/hostname
  shell: echo {{ vagrant_hostname }} > /etc/hostname
  when: hostname is defined

- name: COMMON - Set the hostname
  shell: hostname {{ vagrant_hostname }}
  when: hostname is defined

- name: COMMON - Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ vagrant_hostname }}' owner=root group=root mode=0644
