#roles/php/taks/main.yml
---

# add apt-repository for special php Version
- name: Upgrade for php different Versions  
  apt_repository: repo="{{ php_ppa }}"
  when: php_ppa != ''

- name: install php
  apt: name=php5 state=latest

- name: install php packages
  apt: name={{ item }} state=latest
  with_items: php_packages

# - name: config php.ini
#  lineinfile: dest=/etc/php5/apache2/php.ini
#              regexp='date.timezone ='
#              line='date.timezone = {{ timezone }}'  