#roles/php/taks/main.yml
---

# add apt-repository for special php Version
- name: PHP - Upgrade for php different Versions  
  apt_repository: repo="{{ php_ppa }}"
  when: php_ppa != ''

- name: PHP - Install php
  apt: name=php5 state=latest

- name: PHP - Install php packages
  apt: name={{ item }} state=latest
  with_items: php_packages

- name: PHP - Config php.ini cli
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='{{ item.key }} = '
              line='{{ item.key }} = {{ item.value }}'  
  with_items: php_config_cli

- name: PHP - Config php.ini apache
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='{{ item.key }} = '
              line='{{ item.key }} = {{ item.value }}'  
  with_items: php_config_apache